checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - vendor/*
        - Tests/*

tools:
    external_code_coverage: 
        timeout: 600    # Timeout in seconds.
        runs: 5
