language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit --coverage-clover=clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: helios.ag@gmail.com
